// api/v1/myapp_types.go
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// MyAppSpec defines the desired state of MyApp
type MyAppSpec struct {
	Replicas *int32  `json:"replicas"`
	Image    *string `json:"image"`
}

// MyAppStatus defines the observed state of MyApp
type MyAppStatus struct {
	AvailableReplicas int32 `json:"availableReplicas"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// MyApp is the Schema for the myapps API
type MyApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MyAppSpec   `json:"spec,omitempty"`
	Status MyAppStatus `json:"status,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyAppSpec) DeepCopyInto(out *MyAppSpec) {
	*out = *in

	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}

	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}

}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyAppSpec.
func (in *MyAppSpec) DeepCopy() *MyAppSpec {
	if in == nil {
		return nil
	}
	out := new(MyAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MyApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyApp) DeepCopyInto(out *MyApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyApp.
func (in *MyApp) DeepCopy() *MyApp {
	if in == nil {
		return nil
	}
	out := new(MyApp)
	in.DeepCopyInto(out)
	return out
}

// +kubebuilder:object:root=true

// MyAppList contains a list of MyApp
type MyAppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MyApp `json:"items"`
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MyAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *MyAppList) DeepCopyInto(out *MyAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MyApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyAppList.
func (in *MyAppList) DeepCopy() *MyAppList {
	if in == nil {
		return nil
	}
	out := new(MyAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyAppStatus) DeepCopyInto(out *MyAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyAppStatus.
func (in *MyAppStatus) DeepCopy() *MyAppStatus {
	if in == nil {
		return nil
	}
	out := new(MyAppStatus)
	in.DeepCopyInto(out)
	return out
}
